### ISSUE TITLE
Aint working some Uids

### ISSUE THREAD

**Issue by ShresthVaibhav** [DEViantUA/EnkaNetworkCard#9]
`Traceback (most recent call last):
2023-09-30T12:25:41.802923+00:00 app[worker.1]:   File "/app/cocomodules/mycharacter.py", line 149, in mycharacter
2023-09-30T12:25:41.802923+00:00 app[worker.1]:     profile = await encard.profile(enc = ENCpy)
2023-09-30T12:25:41.802923+00:00 app[worker.1]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-30T12:25:41.802924+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/enkacard/encbanner.py", line 145, in profile
2023-09-30T12:25:41.802924+00:00 app[worker.1]:     itog = await creatUserProfile(image,profile,self.translateLang,self.hide,uid,self.assets,teample)
2023-09-30T12:25:41.802925+00:00 app[worker.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-30T12:25:41.802925+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/enkacard/src/utils/userProfile.py", line 186, in creatUserProfile
2023-09-30T12:25:41.802926+00:00 app[worker.1]:     picturesProfile = await imagSize(link = player.avatar.icon.url,fixed_width = 179)
2023-09-30T12:25:41.802926+00:00 app[worker.1]:                                             ^^^^^^^^^^^^^^^^^^^^^^
2023-09-30T12:25:41.802927+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'url'`

Refrence uid = 877877740

**Comment by DEViantUA** [comment]
Set an avatar in the game
